title: Containerization & DevOps
description: "Lab experiments and theory notes for Containerization & DevOps specialization."
author: Pranav R Nair
email: nairp126@gmail.com # Optional: Add your email if you want

# Build settings
markdown: kramdown
theme: pages-themes/architect@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag

# URL Settings (Important for GitHub Pages)
url: "https://nairp126.github.io" 
baseurl: "/Containerization-and-Devops-" 

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - scripts/
  - LICENSE
  
# Optional: Sidebar settings (if supported by theme)
show_downloads: true
google_analytics: 